export enum ESalonIntro1 {
  en = 'Website for the hair salon "Parturi Kampaamo Hannastiina". The site is implemented with Node.js and React. Node.js serves the React site statically and provides an API interface for managing services. Editing the content of the site requires a username and password.',
  es = 'Sitio web para la peluquería "Parturi Kampaamo Hannastiina". El sitio está implementado con Node.js y React. Node.js sirve el sitio React estáticamente y proporciona una interfaz de API para administrar servicios. La edición del contenido del sitio requiere un nombre de usuario y una contraseña.',
  fr = "Site Web pour le salon de coiffure 'Parturi Kampaamo Hannastiina'. Le site est implémenté avec Node.js et React. Node.js sert le site React de manière statique et fournit une interface API pour gérer les services. La modification du contenu du site nécessite un nom d'utilisateur et un mot de passe.",
  de = 'Website für den Friseursalon "Parturi Kampaamo Hannastiina". Die Website ist mit Node.js und React implementiert. Node.js bedient die React-Website statisch und bietet eine API-Schnittstelle zur Verwaltung von Diensten. Die Bearbeitung des Inhalts der Website erfordert einen Benutzernamen und ein Passwort.',
  pt = 'Site para o salão de cabeleireiro "Parturi Kampaamo Hannastiina". O site é implementado com Node.js e React. Node.js serve o site React estaticamente e fornece uma interface de API para gerenciar serviços. A edição do conteúdo do site requer um nome de usuário e uma senha.',
  cs = 'Webové stránky pro kadeřnictví "Parturi Kampaamo Hannastiina". Stránka je implementována pomocí Node.js a React. Node.js poskytuje React stránku staticky a poskytuje rozhraní API pro správu služeb. Úprava obsahu webu vyžaduje uživatelské jméno a heslo.',
  fi = 'Verkkosivusto Parturi Kampaamo Hannastiina -kampaamolle. Sivusto on toteutettu Node.js:llä ja Reactilla. Node.js palvelee React-sivustoa staattisesti ja tarjoaa rajapinnan palveluiden hallintaan. Sivuston sisällön muokkaaminen vaatii käyttäjätunnuksen ja salasanan.',
}

export enum ESalonIntro2 {
  en = "The site's introduction, categories, users, and services are stored in a MySQL database, managed with Sequelize by logged-in users.",
  es = 'La introducción del sitio, las categorías, los usuarios y los servicios se almacenan en una base de datos MySQL, administrada con Sequelize por usuarios conectados.',
  fr = "L'introduction du site, les catégories, les utilisateurs et les services sont stockés dans une base de données MySQL, gérée avec Sequelize par des utilisateurs connectés.",
  de = 'Die Einführung des Standorts, Kategorien, Benutzer und Dienste werden in einer MySQL-Datenbank gespeichert und von eingeloggten Benutzern mit Sequelize verwaltet.',
  pt = 'A introdução do site, categorias, usuários e serviços são armazenados em um banco de dados MySQL, gerenciado com Sequelize por usuários conectados.',
  cs = 'Úvod webu, kategorie, uživatelé a služby jsou uloženy v databázi MySQL, spravované pomocí Sequelize přihlášenými uživateli.',
  fi = 'Sivuston esittely, kategoriat, käyttäjät ja palvelut tallennetaan MySQL-tietokantaan, jota hallitaan Sequelize:llä kirjautuneiden käyttäjien toimesta.',
}
export enum ESalonIntro3 {
  en = 'There are three main user roles and a fourth testing role. Site owner and site administrators can manage users and services, while authorized users can manage services. Site owner cannot be deleted. The testing role is for viewing purposes only and cannot edit the database.',
  es = 'Hay tres roles principales de usuario y un cuarto rol de prueba. El propietario del sitio y los administradores del sitio pueden administrar usuarios y servicios, mientras que los usuarios autorizados pueden administrar servicios. El propietario del sitio no se puede eliminar. El rol de prueba es solo para fines de visualización y no puede editar la base de datos.',
  fr = "Il existe trois rôles principaux d'utilisateur et un quatrième rôle de test. Le propriétaire du site et les administrateurs du site peuvent gérer les utilisateurs et les services, tandis que les utilisateurs autorisés peuvent gérer les services. Le propriétaire du site ne peut pas être supprimé. Le rôle de test est uniquement à des fins de visualisation et ne peut pas modifier la base de données.",
  de = 'Es gibt drei Hauptbenutzerrollen und eine vierte Testrolle. Der Website-Besitzer und die Website-Administratoren können Benutzer und Dienste verwalten, während autorisierte Benutzer Dienste verwalten können. Der Website-Besitzer kann nicht gelöscht werden. Die Testrolle dient nur zur Anzeige und kann die Datenbank nicht bearbeiten.',
  pt = 'Existem três funções principais de usuário e uma quarta função de teste. O proprietário do site e os administradores do site podem gerenciar usuários e serviços, enquanto os usuários autorizados podem gerenciar serviços. O proprietário do site não pode ser excluído. A função de teste é apenas para fins de visualização e não pode editar o banco de dados.',
  cs = 'Existují tři hlavní uživatelské role a čtvrtá testovací role. Majitel webu a správci webu mohou spravovat uživatele a služby, zatímco autorizovaní uživatelé mohou spravovat služby. Majitel webu nemůže být smazán. Testovací role je pouze pro účely zobrazení a nemůže upravovat databázi.',
  fi = 'Kolmen käyttäjäroolin lisäksi on neljäs testaajarooli. Sivuston omistaja ja sivuston ylläpitäjät voivat hallinnoida käyttäjiä ja palveluita, ja valtuutetut käyttäjät voivat hallinnoida palveluita. Sivuston omistajaa ei voi poistaa. Testaajarooli on vain tarkastelua varten, eikä voi muokata tietokantaa.',
}
